#!/usr/bin/env php
<?php
error_reporting(0);
ini_set('display_errors', 'on');
ini_set('limit_memory', '512M');
ini_set('opcache.enable', false);
date_default_timezone_set('Asia/Shanghai');

define('NHK_PATH_ROOT', realpath(__DIR__) . DIRECTORY_SEPARATOR);
define('NHK_PATH_CONF', NHK_PATH_ROOT . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR);
define('NHK_PATH_SYSTEM', NHK_PATH_ROOT . 'system' . DIRECTORY_SEPARATOR);

if ($argc < 2) {
    showUsage();
}

$cmd = $argv[1];

require_once NHK_PATH_SYSTEM . 'core.php';

// Enable the auto-loader.
spl_autoload_register(array('NHK\System\Core', 'autoLoad'));

NHK\System\Env::getInstance()->test();
NHK\System\Core::init();
$master = new \NHK\Server\Master();

switch ($cmd) {
    case 'start':
        $master->run();
        break;
    case 'stop':
        NHK\System\Process::stop();
        break;
    case 'restart':
        NHK\System\Process::stop();
        $master->run();
        break;
    case 'reload':
        NHK\System\Process::reload();
        break;
    case 'kill':
        NHK\System\Process::killMaster();
        break;
    case 'status':
        NHK\System\Process::status();
        break;
    case 'version':
        NHK\System\Env::getVersion();
        break;
    default:
        showUsage();
        break;
}

function showUsage() {
    printf("Usage: %s {start|stop|restart|reload|kill|status|version}\n", __FILE__);
    exit(0);
}